namespace DevoidEngine.Engine.Core
{
    using KeysAlias = OpenTK.Windowing.GraphicsLibraryFramework.Keys;

    public enum Keys
    {
        Unknown = KeysAlias.Unknown,

        // Letters
        A = KeysAlias.A,
        B = KeysAlias.B,
        C = KeysAlias.C,
        D = KeysAlias.D,
        E = KeysAlias.E,
        F = KeysAlias.F,
        G = KeysAlias.G,
        H = KeysAlias.H,
        I = KeysAlias.I,
        J = KeysAlias.J,
        K = KeysAlias.K,
        L = KeysAlias.L,
        M = KeysAlias.M,
        N = KeysAlias.N,
        O = KeysAlias.O,
        P = KeysAlias.P,
        Q = KeysAlias.Q,
        R = KeysAlias.R,
        S = KeysAlias.S,
        T = KeysAlias.T,
        U = KeysAlias.U,
        V = KeysAlias.V,
        W = KeysAlias.W,
        X = KeysAlias.X,
        Y = KeysAlias.Y,
        Z = KeysAlias.Z,

        // Numbers (top row)
        D0 = KeysAlias.D0,
        D1 = KeysAlias.D1,
        D2 = KeysAlias.D2,
        D3 = KeysAlias.D3,
        D4 = KeysAlias.D4,
        D5 = KeysAlias.D5,
        D6 = KeysAlias.D6,
        D7 = KeysAlias.D7,
        D8 = KeysAlias.D8,
        D9 = KeysAlias.D9,

        // Function keys
        F1 = KeysAlias.F1,
        F2 = KeysAlias.F2,
        F3 = KeysAlias.F3,
        F4 = KeysAlias.F4,
        F5 = KeysAlias.F5,
        F6 = KeysAlias.F6,
        F7 = KeysAlias.F7,
        F8 = KeysAlias.F8,
        F9 = KeysAlias.F9,
        F10 = KeysAlias.F10,
        F11 = KeysAlias.F11,
        F12 = KeysAlias.F12,
        F13 = KeysAlias.F13,
        F14 = KeysAlias.F14,
        F15 = KeysAlias.F15,
        F16 = KeysAlias.F16,
        F17 = KeysAlias.F17,
        F18 = KeysAlias.F18,
        F19 = KeysAlias.F19,
        F20 = KeysAlias.F20,
        F21 = KeysAlias.F21,
        F22 = KeysAlias.F22,
        F23 = KeysAlias.F23,
        F24 = KeysAlias.F24,
        F25 = KeysAlias.F25,

        // Modifiers
        LeftShift = KeysAlias.LeftShift,
        LeftControl = KeysAlias.LeftControl,
        LeftAlt = KeysAlias.LeftAlt,
        LeftSuper = KeysAlias.LeftSuper,
        RightShift = KeysAlias.RightShift,
        RightControl = KeysAlias.RightControl,
        RightAlt = KeysAlias.RightAlt,
        RightSuper = KeysAlias.RightSuper,

        // Navigation
        Up = KeysAlias.Up,
        Down = KeysAlias.Down,
        Left = KeysAlias.Left,
        Right = KeysAlias.Right,
        PageUp = KeysAlias.PageUp,
        PageDown = KeysAlias.PageDown,
        Home = KeysAlias.Home,
        End = KeysAlias.End,
        Insert = KeysAlias.Insert,
        Delete = KeysAlias.Delete,

        // Other controls
        Escape = KeysAlias.Escape,
        Enter = KeysAlias.Enter,
        Tab = KeysAlias.Tab,
        Backspace = KeysAlias.Backspace,
        Space = KeysAlias.Space,
        CapsLock = KeysAlias.CapsLock,
        ScrollLock = KeysAlias.ScrollLock,
        NumLock = KeysAlias.NumLock,
        PrintScreen = KeysAlias.PrintScreen,
        Pause = KeysAlias.Pause,

        // Keypad
        KP0 = KeysAlias.KeyPad0,
        KP1 = KeysAlias.KeyPad1,
        KP2 = KeysAlias.KeyPad2,
        KP3 = KeysAlias.KeyPad3,
        KP4 = KeysAlias.KeyPad4,
        KP5 = KeysAlias.KeyPad5,
        KP6 = KeysAlias.KeyPad6,
        KP7 = KeysAlias.KeyPad7,
        KP8 = KeysAlias.KeyPad8,
        KP9 = KeysAlias.KeyPad9,
        KPDecimal = KeysAlias.KeyPadDecimal,
        KPDivide = KeysAlias.KeyPadDivide,
        KPMultiply = KeysAlias.KeyPadMultiply,
        KPSubtract = KeysAlias.KeyPadSubtract,
        KPAdd = KeysAlias.KeyPadAdd,
        KPEnter = KeysAlias.KeyPadEnter,
        KPEqual = KeysAlias.KeyPadEqual,

        // Symbols
        Minus = KeysAlias.Minus,
        Equal = KeysAlias.Equal,
        LeftBracket = KeysAlias.LeftBracket,
        RightBracket = KeysAlias.RightBracket,
        Backslash = KeysAlias.Backslash,
        Semicolon = KeysAlias.Semicolon,
        Apostrophe = KeysAlias.Apostrophe,
        GraveAccent = KeysAlias.GraveAccent,
        Comma = KeysAlias.Comma,
        Period = KeysAlias.Period,
        Slash = KeysAlias.Slash,

        // Extra
        Menu = KeysAlias.Menu
    }
}
